### ISSUE TITLE
`{filename}` from URL leaks from summary of the very first post

### ISSUE THREAD

**Issue by arturlangner** [MinchinWeb/minchin.pelican.plugins.summary#5]
Thank you a lot for this nice plugin.

Internal URLs in the **very first post summary** (on the home page) contain raw `{filename}` and the link is broken. I am not sure if it is a bug in the plugin or in Pelican itself.

The URLs are okay after opening the full article page. The URLs are okay in summaries further down on the home page.

It seems like the internal URL in the affected summary is not transformed from Markdown in any way and looks like `<a href="{filename}/articles/2021/somearticle.md">design</a>`.

RSS feed is also affected.

I am using `minchin.pelican.plugins.summary 1.2.0` via `pip`.

# Affected site example
https://m0agx.eu

* View source and Ctrl+F `{filename}` for a broken internal link.
* View source and Ctrl+F `din-rail` for a working internal link.

**Comment by arturlangner** [comment]
Bug is in Pelican itself. https://github.com/getpelican/pelican/issues/3265

**Comment by MinchinWeb** [comment]
@arturlangner In the end, how did you fix this? Did you upgrade Pelican version (or something else)?

**Comment by MinchinWeb** [comment]
c.f. #4

**Comment by MinchinWeb** [comment]
The current version of Pelican is 4.9.1, and I expect the fix to be in the next version released.
