### ISSUE TITLE
Plugin either not loading with pelican 4.8 or conflicting somehow with read_more plugin

### ISSUE THREAD

**Issue by guru-das-s** [MinchinWeb/minchin.pelican.plugins.summary#6]
I just tried installing this plugin alongside the `read_more` plugin, with `SUMMARY_USE_FIRST_PARAGRAPH = True` enabled in `pelicanconf.py`.

My expectation was that in my index page, the summary would be just the first paragraph of my blogpost but instead I see the Read More link. I also tried manually adding `'minchin.pelican.plugins.summary'` to `PLUGINS` - that resulted in no errors (so I know the plugin is being loaded correctly) but I still see don't see the effects of it working. 

Could you please help? I would like to retain the `read_more` plugin for my older posts so I wonder if your plugin can coexist with it. Thank you so much!

**Comment by MinchinWeb** [comment]
Thanks for reaching out; it's nice to know the plugin is used :)

I'm looking at the `read_more` plugin and I don't think the two will work together.

`read_more` generates it's own summary, and so it blows away any existing summary (see [here](https://github.com/pelican-plugins/read-more/blob/main/pelican/plugins/read_more/read_more.py#L72-L74)), while my plugin (`minchin.pelican.plugins.summary`) will default to an existing summary if one is in place (see [here](https://github.com/MinchinWeb/minchin.pelican.plugins.summary/blob/master/minchin/pelican/plugins/summary/summary.py#L66-L70)), either from another plugin or from the entry metadata.

So if `read_more` runs first, `minchin.pelican.plugins.summary` won't do anything, as there is an existing summary. If `minchin.pelican.plugins.summary` runs first, the generated summary will be blown away by `read_more`.

That said, moving to `minchin.pelican.plugins.summary` shouldn't be too hard. If you want to control where the summary ends, you can add a `<!-- PELICAN_END_SUMMARY -->` line in your source Markdown. (This is an HTML comment, so it shouldn't be visible on the generated site even if it doesn't get removed for some reason, like dropping this plugin in the future.) You may need to add a "Read More" link to your theme; if you need help with that, let me know; here's how I do it in [my theme](https://github.com/MinchinWeb/seafoam/blob/master/pelican/plugins/seafoam/templates/includes/article_listing.html#L61-L65).
